# Generated by Django 2.2 on 2020-05-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_tracking', '0008_auto_20200201_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequestlog',
            name='verb',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='apirequestlog',
            name='username_persistent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
